version: "3"
services:
  db:
    build:
      context: ./.docker/postgres/
      dockerfile: Dockerfile
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-postgres}
      LANG: ${DB_LANG:-ja_JP.UTF-8}
      TZ: ${TZ:-Asia/Tokyo}
    volumes:
      - ./.docker-volumes/postgres/data:/var/lib/postgresql/data
  pg_proxy:
    image: ghcr.io/neondatabase/wsproxy:latest
    environment:
      APPEND_PORT: "postgres:5432"
      ALLOW_ADDR_REGEX: ".*"
      LOG_TRAFFIC: "true"
    ports:
      - "5433:80"
    depends_on:
      - db
  adminer:
    image: adminer
    ports:
      - ${ADMINER_PORT:-8080}:8080
    environment:
      ADMINER_DEFAULT_SERVER: ${DB_HOST:-db}
      ADMINER_DEFAULT_USERNAME: ${DB_USER:-postgres}
      ADMINER_DEFAULT_PASSWORD: ${DB_PASSWORD:-postgres}
      ADMINER_DESIGN: ${ADMINER_DESIGN:-nette}
    depends_on:
      - db